teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1  # Left stick up/down
    scale_linear:
      x: 1.0 
      
    axis_angular:
      yaw: 3  # Right stick left/right
    scale_angular:
      yaw: 0.5  
      
    enable_button: 4  # Right Bumper (RB) must be held down to drive
    
    enable_turbo_button: 5  # Left Bumper (LB)
    scale_linear_turbo:
      x: 2.0